resolver: lts-20.26

packages:
- .

extra-deps: 
 - weierstrass-functions-0.1.1.0
 - elliptic-integrals-0.1.0.1
 - jacobi-theta-0.1.2.0
 - gamma-0.10.0.0
 - continued-fractions-0.10.0.2
 - converge-0.1.0.1
 - numeric-tools-0.2.0.1
