resolver: lts-20.26

packages:
- .

extra-deps: 
 - git: https://github.com/stla/weierstrass-functions.git
   commit: 92130c776dcc27b479956c34355a55df63b3b50c
 - elliptic-integrals-0.1.0.1
 - git: https://github.com/stla/jacobi-theta.git
   commit: bec442d433a2c7ce39229e6a89232779d32db596
 - gamma-0.10.0.0
 - continued-fractions-0.10.0.2
 - converge-0.1.0.1
 - numeric-tools-0.2.0.1
 - hsluv-haskell-0.1.0.0
 - BesselJ-0.2.0.0
 - numerical-integration-0.1.2.3
